{
 "title": "Teams Overview",
 "tags": [ "Teams" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "baseServiceUri", "query": "https://192.168.1.196" }
  ]
 },
 "panels": [
  {
   "title": "Total Number of Teams",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT TOP(50) COUNT(*) FROM dbo.OrganizationView "
    }
   ]
  },
  {
   "title": "Average Member Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT AVG(\"count\")\r\nFROM (\r\n  SELECT OrganizationId, COUNT(*) \"count\" FROM dbo.OrganizationUserView GROUP BY OrganizationId \r\n  ) \"data\""
    }
   ]
  },
  {
   "title": "Top 10 Teams with Most Secrets",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "  SELECT TOP(10) Organization.Name , COUNT(*) \"count\"\r\n  FROM dbo.Cipher \r\n  JOIN Organization ON Organization.Id = OrganizationId\r\n  WHERE OrganizationId IS NOT NULL \r\n  GROUP BY Organization.Name \r\n  ORDER BY COUNT(*) DESC\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Teams with Most Members",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "  SELECT TOP(50) Organization.Name , COUNT(*) \"count\"\r\n  FROM dbo.OrganizationUserView \r\n  JOIN Organization ON Organization.Id = OrganizationId\r\n  WHERE OrganizationId IS NOT NULL \r\n  GROUP BY Organization.Name \r\n  ORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Teams Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT \r\n  \"Name\", \r\n  CreationDate, \r\n  (SELECT COUNT(*) FROM Cipher WHERE Cipher.OrganizationId = OrganizationView.Id) \"secrets\", \r\n  (SELECT COUNT(*) FROM OrganizationUser WHERE OrganizationUser.OrganizationId = OrganizationView.Id) \"members\", \r\n  (SELECT COUNT(*) FROM \"Collection\" WHERE \"Collection\".OrganizationId = OrganizationView.Id) \"collections\",\r\n  RevisionDate \r\nFROM OrganizationView;"
    }
   ]
  }
 ]
}