{
 "title": "Team Details",
 "description": "Team specific information, statistics, and events",
 "tags": [ "Teams" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OrganizationName",
    "label": "Team selection",
    "query": "SELECT \"Name\" FROM dbo.OrganizationView"
   },
   {
    "name": "UserName",
    "label": "User selection",
    "query": "SELECT UserView.Name \nFROM OrganizationUserView\nJOIN OrganizationView ON OrganizationUserView.OrganizationId = OrganizationView.Id\nJOIN UserView ON OrganizationUserView.UserId = UserView.Id\nWHERE OrganizationView.\"Name\" = '$OrganizationName';"
   }
  ]
 },
 "panels": [
  {
   "title": "Team Statistics",
   "type": "table",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT \r\n  \"Name\", \r\n  CreationDate, \r\n  (SELECT COUNT(*) FROM Cipher WHERE Cipher.OrganizationId = OrganizationView.Id) \"secrets\", \r\n  (SELECT COUNT(*) FROM OrganizationUser WHERE OrganizationUser.OrganizationId = OrganizationView.Id) \"members\", \r\n  (SELECT COUNT(*) FROM \"Collection\" WHERE \"Collection\".OrganizationId = OrganizationView.Id) \"collections\",\r\n  RevisionDate \r\nFROM OrganizationView\r\nWHERE \"Name\" = '$OrganizationName';"
    }
   ]
  },
  {
   "title": "General Team Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT CAST( EventView.Date AS DATE) AS \"time\", EventType.event \"Event\", COUNT(*)\r\nFROM EventView \r\nJOIN OrganizationView ON OrganizationView.Id = EventView.OrganizationId\r\nJOIN metadata.EventType ON EventView.Type = EventType.code \r\nWHERE OrganizationView.Name = '$OrganizationName'\r\nGROUP BY CAST( EventView.Date AS DATE), \"Event\"\r\nORDER BY CAST( EventView.Date AS DATE) ASC\r\n;"
    },
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT CAST( EventView.Date AS DATE) AS \"time\", COUNT(*) \"Total Number of Events\"\r\nFROM EventView \r\nJOIN OrganizationView ON OrganizationView.Id = EventView.OrganizationId\r\nWHERE OrganizationView.Name = '$OrganizationName'\r\nGROUP BY CAST( EventView.Date AS DATE)\r\nORDER BY CAST( EventView.Date AS DATE) ASC\r\n;\r\n"
    }
   ]
  },
  {
   "title": "Team Membership",
   "type": "table",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT UserView.Name \"User Name\", UserView.Email, OrganizationUserType.type \"Role\", UserView.\"CreationDate\" AS \"Join Date\"\r\nFROM dbo.OrganizationView\r\nJOIN dbo.OrganizationUser ON OrganizationView.Id = OrganizationUser.OrganizationId\r\nJOIN dbo.UserView ON OrganizationUser.UserId = UserView.Id\r\nJOIN metadata.OrganizationUserType ON OrganizationUserType.code = OrganizationUser.type\r\nWHERE OrganizationView.\"Name\" = '$OrganizationName' AND UserView.Name IN ($UserName)\r\nORDER BY UserView.Name ASC;"
    }
   ]
  },
  {
   "title": "Team Members Event Log",
   "type": "table",
   "gridPos": { "h": 16, "w": 10, "x": 10, "y": 12 },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT EventView.Date, UserView.Name, EventType.event, EventView.DeviceType\r\nFROM EventView \r\nJOIN OrganizationView ON OrganizationView.Id = EventView.OrganizationId\r\nJOIN UserView ON UserView.Id = EventView.ActingUserId\r\nJOIN metadata.EventType ON EventView.Type = EventType.code \r\nWHERE OrganizationView.Name = '$OrganizationName' AND UserView.Name IN ($UserName)\r\nORDER BY \"Date\" DESC\r\n;\r\n"
    }
   ]
  }
 ]
}