{
 "title": "Secrets Overview",
 "description": "Describe Secrets Trends over Time",
 "tags": [ "Secrets" ],
 "time": { "from": "2022-06-17T00:34:02.132Z", "to": "2022-08-13T10:35:01.524Z" },
 "panels": [
  {
   "title": "Breakdown of Secrets by Type",
   "type": "piechart",
   "description": "Breakdown by type of stored Secrets",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT TOP(50) COUNT(*) \"Logins\" FROM Cipher WHERE \"Type\" = 1"
    },
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT TOP(50) COUNT(*) \"Secure Notes\" FROM Cipher WHERE \"Type\" = 2"
    },
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT TOP(50) COUNT(*) \"Cards\" FROM dbo.Cipher WHERE \"Type\" = 1"
    },
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT TOP(50) COUNT(*) \"Identities\" FROM dbo.Cipher WHERE \"Type\" = 1"
    }
   ]
  },
  {
   "title": "Total Number of User Secrets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT TOP(50) COUNT(*) FROM Cipher WHERE \"UserId\" IS NOT NULL"
    }
   ]
  },
  {
   "title": "Total Number of Secrets stored in Teams",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT TOP(50) COUNT(*) FROM Cipher WHERE \"UserId\" IS NULL"
    }
   ]
  },
  {
   "title": "Average Number of Secrets per User",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT COUNT(*) FROM Cipher WHERE UserId IS NOT NULL\r\nUNION ALL\r\nSELECT ( SELECT COUNT(*) FROM Cipher WHERE UserId IS NOT NULL ) / ( SELECT COUNT(*) FROM \"User\" );\r\n\r\n"
    }
   ]
  },
  {
   "title": "Average Number of Secrets per Team",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT COUNT(*) FROM Cipher WHERE UserId IS NULL\r\nUNION ALL\r\nSELECT ( SELECT COUNT(*) FROM Cipher WHERE UserId IS NULL ) / ( SELECT COUNT(*) FROM OrganizationView );\r\n\r\n"
    }
   ]
  },
  {
   "title": "Secrets Created by Day by Type",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT CAST(Date AS DATE) AS \"time\", COUNT(*) AS \"Passwords\" \r\nFROM EventView \r\nJOIN Cipher ON Cipher.Id = EventView.CipherId\r\nWHERE EventView.\"Type\" = 1100 AND Cipher.\"Type\" = 1\r\nGROUP BY CAST(Date AS DATE)"
    },
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT CAST(Date AS DATE) AS \"time\", COUNT(*) AS \"Secure Notes\" \r\nFROM EventView \r\nJOIN Cipher ON Cipher.Id = EventView.CipherId\r\nWHERE EventView.\"Type\" = 1100 AND Cipher.\"Type\" = 2\r\nGROUP BY CAST(Date AS DATE)"
    },
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT CAST(Date AS DATE) AS \"time\", COUNT(*) AS \"Card\" \r\nFROM EventView \r\nJOIN Cipher ON Cipher.Id = EventView.CipherId\r\nWHERE EventView.\"Type\" = 1100 AND Cipher.\"Type\" = 3\r\nGROUP BY CAST(Date AS DATE)"
    },
    {
     "dataset": "vaultDev",
     "rawSql": "SELECT CAST(Date AS DATE) AS \"time\", COUNT(*) AS \"Identities\" \r\nFROM EventView \r\nJOIN Cipher ON Cipher.Id = EventView.CipherId\r\nWHERE EventView.\"Type\" = 1100 AND Cipher.\"Type\" = 4\r\nGROUP BY CAST(Date AS DATE)"
    }
   ]
  }
 ]
}