<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\Infrastructure.Dapper\Infrastructure.Dapper.csproj" />
      <ProjectReference Include="..\Core\Core.csproj" />
      <ProjectReference Include="..\Infrastructure.EntityFramework\Infrastructure.EntityFramework.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Formats.Asn1" Version="8.0.1" />
      <PackageReference Include="System.Security.Cryptography.Xml" Version="7.0.2" />
      <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    </ItemGroup>

</Project>
